### PR TITLE
Added submission using our new PR Bot.

### PR DESCRIPTION
**Pull request by j-rewerts**
Creates a basic PR from the form. It has a few problems right now:
1. It just completely overwrites the file in `_data/code/{GOV_TYPE}/{LOCALITY_CODE}, if it exists.
2. We don't have {GOV_TYPE} in the forms right now. We'll need to collect it.
3. We aren't configuring based on the actual git root. We should allow this to be configured so it works on people's forks.

Check out an example PR this generated [here](https://github.com/j-rewerts/ore-ero/pull/4).

### CODE REVIEW

**Comment by j-rewerts** [comment]
I've got #1 partly sorted out now. [This](https://github.com/j-rewerts/ore-ero/pull/14) is what a PR looks like. Now I can't handle creating files if they don't exist. I'll have to take a look at that tomorrow.

**Comment by j-rewerts** [comment]
I've resolved issues 1, 2 and 3. I can now successfully add new projects as well as update existing projects. If the organization doesn't have a file in data/code/{org level}, then it creates one with the PR. I've got 1 issue I can't seem to resolve now.

The YAML library I'm using is opinionated and will apply its own formatting, which changes our documents in ways we may not expect. @imadeDev I'm hoping to get your thoughts on this, since you've been working on defining our Yaml spec.
Check out [this](https://github.com/j-rewerts/ore-ero/pull/19/files) PR for an example of what I'm talking about. Notice it edits YouCanBenefit, even though I'm adding a new project as well. It does things like replace " with ' and changes spacing. 

If that issue is considered acceptable, I think we can probably merge this in and start working on the user friendliness of the form, since I don't even tell the user their submission was successful yet.

**Comment by j-rewerts** [comment]
Check out [this](https://github.com/j-rewerts/ore-ero/pull/21) PR for an example of a totally new file creation.

**Comment by j-rewerts** [comment]
Check out [this PR](https://github.com/j-rewerts/ore-ero/pull/22/commits) for an example of me setting the commit author. We can set that to any username or email without authenticating the user to GitHub, so it's worth noting that may not be the person that actually submitted the form.

Right now, I'm pulling this info from the `#nameContact` and `#emailContact` fields in our form.

**Comment by smellems** [comment]
Hi @j-rewerts !

Not sure about the YAML parsing.  I'd like to get others' ideas.  In French there are a lot of single quotes.  You would have to know to double them.  But I guess if your editing the YAML directly, you might know.. The date format is also more complicated.  I also notice that it replaced the `é` with `Ã©`. Does it use UTF-8?  It would be nice to have a consistent format. We could update existing files..

It looks like we wont be using Isomorphic-Git, but a few other libraries and utilities.  It would be good to document these.  pr-bot, heroku, object-base, yaml, ..  this should be another PR.

The build is failing and it all looks fixable.
https://travis-ci.com/j-rewerts/ore-ero/builds/109377092

**Comment by imadeDev** [comment]
> I've resolved issues 1, 2 and 3. I can now successfully add new projects as well as update existing projects. If the organization doesn't have a file in data/code/{org level}, then it creates one with the PR. I've got 1 issue I can't seem to resolve now.
> 
> The YAML library I'm using is opinionated and will apply its own formatting, which changes our documents in ways we may not expect. @imadeDev I'm hoping to get your thoughts on this, since you've been working on defining our Yaml spec.
> Check out [this](https://github.com/j-rewerts/ore-ero/pull/19/files) PR for an example of what I'm talking about. Notice it edits YouCanBenefit, even though I'm adding a new project as well. It does things like replace " with ' and changes spacing.
> 
> If that issue is considered acceptable, I think we can probably merge this in and start working on the user friendliness of the form, since I don't even tell the user their submission was successful yet.

HHi @j-rewerts ! I will check with yamale how I can solve this formatting problem

**Comment by imadeDev** [comment]
> I've resolved issues 1, 2 and 3. I can now successfully add new projects as well as update existing projects. If the organization doesn't have a file in data/code/{org level}, then it creates one with the PR. I've got 1 issue I can't seem to resolve now.
> 
> The YAML library I'm using is opinionated and will apply its own formatting, which changes our documents in ways we may not expect. @imadeDev I'm hoping to get your thoughts on this, since you've been working on defining our Yaml spec.
> Check out [this](https://github.com/j-rewerts/ore-ero/pull/19/files) PR for an example of what I'm talking about. Notice it edits YouCanBenefit, even though I'm adding a new project as well. It does things like replace " with ' and changes spacing.
> 
> If that issue is considered acceptable, I think we can probably merge this in and start working on the user friendliness of the form, since I don't even tell the user their submission was successful yet.

Hi @j-rewerts ! I will check with yamale how I can solve this formatting problem

**Comment by j-rewerts** [comment]
@smellems Totally forgot about the encoding issue! I'll look into resolving that. 
I'll also take a look at our linters and see what the issues are. 
What is the best place to document our dependencies? 

In terms of PRB0t, I could probably set up auto deployment for it from our root ore-ero repo. Right now I'm maintaining a hard fork of PRB0t that has our improvements, but I think I'll be able to get my changes into upstream. After that, we'll still want our own deployment of it. Any thoughts on this?

**Comment by j-rewerts** [comment]
I've identified the encoding issue is in PRB0t, not my new YAML library. I'll do a little digging and see if I can fix it.

**Comment by j-rewerts** [comment]
Looks like PRB0t actually fixed this issue since I forked from it, so I just had to update our fork. Open source working as hoped! 👍

**Comment by j-rewerts** [comment]
@smellems I think I've addressed all feedback. I'll work with @imadeDev on the schema side of things over the next little while to make sure my YAML library plays nice with his validator. I'm hoping we can make any changes in a separate PR (if needed).

**Comment by smellems** [comment]
@j-rewerts I made the pull request https://github.com/canada-ca/ore-ero/pull/128

Could you fix the conflict in the footer?  Also if you create the pull request it will be easier to give you the credit for the work

**Comment by j-rewerts** [comment]
@smellems Sure! I'll submit the PR to the root repo.

**Pull request closed without merging**
